# Generated by Django 5.1.1 on 2024-10-27 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Quản trị viên'), ('warehouse_staff', 'Kho'), ('sales_staff', 'Sale'), ('technician', 'Kỹ thuật'), ('finance_staff', 'Nghiệp vụ'), ('team_R&D', 'R&D'), ('CEO', 'Giám Đốc')], default='sales_staff', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_Receipts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_date', models.DateField()),
                ('other_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('net_weight', models.FloatField()),
                ('net_price', models.FloatField()),
                ('sales_unit', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_Entries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stt', models.IntegerField(blank=True, null=True)),
                ('entry_date', models.DateField()),
                ('quantity', models.IntegerField(blank=True)),
                ('bills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.bills')),
                ('contracts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.contracts')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.products')),
                ('suppliers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.suppliers')),
                ('warehouse_receipts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.warehouse_receipts')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
    ]
